// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stationery.Data;

#nullable disable

namespace Stationery.Migrations
{
    [DbContext(typeof(StationeryDbContext))]
    [Migration("20260822200154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Stationery.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Faber-Castell"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rotring"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stabilo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gıpta"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Moleskine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Keskin Color"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Carioca"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Limit Yayınları"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bilgi Sarmal"
                        },
                        new
                        {
                            Id = 12,
                            Name = "3D Yayınları"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Çap Yayınları"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hız Yayınları"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Palme Yayınevi"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Tonguç Akademi"
                        },
                        new
                        {
                            Id = 17,
                            Name = "MAS"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Maped"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pritt"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Milan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Navigator"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Mopak"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ve-Ge"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Eastpak"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Noki"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Esselte"
                        });
                });

            modelBuilder.Entity("Stationery.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Stationery.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Stationery.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Uçlu, tükenmez, kurşun vb.",
                            Name = "Kalemler"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spiralli, dikişli, kareli ve çizgili defterler",
                            Name = "Defterler"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kuru, sulu, pastel boyalar",
                            Name = "Boya Kalemleri"
                        },
                        new
                        {
                            Id = 4,
                            Description = "LGS, YKS, KPSS hazırlık ve soru bankaları",
                            Name = "Test Kitapları"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Zımba, bant, makas, ataş",
                            Name = "Ofis & Masaüstü"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sınav silgileri, mekanik kalemtıraşlar",
                            Name = "Silgi & Kalemtıraş"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fotokopi kağıtları, notluklar",
                            Name = "Kağıt Ürünleri"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Okul çantaları ve beslenme kapları",
                            Name = "Çanta & Beslenme"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Klasörler, poşet dosyalar",
                            Name = "Dosyalama"
                        });
                });

            modelBuilder.Entity("Stationery.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Stationery.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Stationery.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Versatil Kalem",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+Grip+2011",
                            Name = "Faber-Castell Grip 2011 0.7mm",
                            Price = 250m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Uçlu Kalem",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+Tri+Click",
                            Name = "Faber-Castell Tri-Click 0.5mm",
                            Price = 45m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Mekanik Kalem",
                            ImageUrl = "https://placehold.co/400x400?text=Rotring+Tikky",
                            Name = "Rotring Tikky 0.7mm Bordo",
                            Price = 185m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Profesyonel Çizim Kalemi",
                            ImageUrl = "https://placehold.co/400x400?text=Rotring+500",
                            Name = "Rotring 500 0.5mm Siyah",
                            Price = 450m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Fosforlu Kalem",
                            ImageUrl = "https://placehold.co/400x400?text=Stabilo+Boss",
                            Name = "Stabilo Boss Original Sarı",
                            Price = 55m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "İnce Uçlu Keçeli",
                            ImageUrl = "https://placehold.co/400x400?text=Stabilo+Point+88",
                            Name = "Stabilo Point 88 10'lu Set",
                            Price = 320m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Sınav Kalemi",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Kursun+Kalem",
                            Name = "Adel Blackline Kurşun Kalem",
                            Price = 15m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Öğrenci Uçlu Kalem",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Versatil",
                            Name = "Adel 0.7mm Versatil",
                            Price = 35m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Klasik Tükenmez",
                            ImageUrl = "https://placehold.co/400x400?text=Bic+Cristal",
                            Name = "Bic Cristal Mavi Tükenmez 5'li",
                            Price = 45m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Çoklu Tükenmez",
                            ImageUrl = "https://placehold.co/400x400?text=Bic+4+Renk",
                            Name = "Bic 4 Renk Tükenmez Kalem",
                            Price = 85m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Spiralli Defter",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+A4+Defter",
                            Name = "Faber-Castell A4 Çizgili 96 Yp",
                            Price = 85m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Sert Kapak",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+A5+Defter",
                            Name = "Faber-Castell A5 Kareli 80 Yp",
                            Price = 65m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "Seperatörlü Defter",
                            ImageUrl = "https://placehold.co/400x400?text=Gipta+A4+Defter",
                            Name = "Gıpta A4 120 Yaprak 5 Bölmeli",
                            Price = 185m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "Çizgisiz Not Defteri",
                            ImageUrl = "https://placehold.co/400x400?text=Gipta+Notluk",
                            Name = "Gıpta A5 Pastel Notluk",
                            Price = 55m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "Kılavuz Çizgili",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Yazi+Defteri",
                            Name = "Adel İlkokul Güzel Yazı Defteri",
                            Price = 25m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 7,
                            CategoryId = 2,
                            Description = "Deri Kapaklı Ajanda",
                            ImageUrl = "https://placehold.co/400x400?text=Moleskine+Classic",
                            Name = "Moleskine Classic Pocket Siyah",
                            Price = 850m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 7,
                            CategoryId = 2,
                            Description = "İnce Not Defteri",
                            ImageUrl = "https://placehold.co/400x400?text=Moleskine+Cahier",
                            Name = "Moleskine Cahier Journal 3'lü",
                            Price = 450m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 8,
                            CategoryId = 2,
                            Description = "120gr Kağıt",
                            ImageUrl = "https://placehold.co/400x400?text=Keskin+Color+Resim",
                            Name = "Keskin Color A4 Spiralli Resim Defteri",
                            Price = 95m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 8,
                            CategoryId = 2,
                            Description = "Dikişli",
                            ImageUrl = "https://placehold.co/400x400?text=Keskin+Color+Muzik",
                            Name = "Keskin Color Müzik Defteri",
                            Price = 35m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Karton Kutu",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+24lu+Kuru+Boya",
                            Name = "Faber-Castell 24'lü Kuru Boya",
                            Price = 275m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Fırça Hediyeli",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+12li+Sulu+Boya",
                            Name = "Faber-Castell 12'li Sulu Boya",
                            Price = 145m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 4,
                            CategoryId = 3,
                            Description = "Çanta Boy",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Pastel+Boya",
                            Name = "Adel 12'li Yağlı Pastel Boya",
                            Price = 85m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 4,
                            CategoryId = 3,
                            Description = "Yarım Boy",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Kuru+Boya",
                            Name = "Adel 12'li Kuru Boya",
                            Price = 65m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 3,
                            CategoryId = 3,
                            Description = "Bebek/Çocuk Boyası",
                            ImageUrl = "https://placehold.co/400x400?text=Stabilo+Woody",
                            Name = "Stabilo Woody 3 in 1 10'lu",
                            Price = 650m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 9,
                            CategoryId = 3,
                            Description = "Yıkanabilir",
                            ImageUrl = "https://placehold.co/400x400?text=Carioca+Joy",
                            Name = "Carioca Joy 12'li Keçeli Kalem",
                            Price = 125m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 9,
                            CategoryId = 3,
                            Description = "Kalın Uçlu",
                            ImageUrl = "https://placehold.co/400x400?text=Carioca+Jumbo",
                            Name = "Carioca Jumbo 6'lı Keçeli",
                            Price = 110m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 10,
                            CategoryId = 4,
                            Description = "Yeni Müfredat",
                            ImageUrl = "https://placehold.co/400x400?text=Limit+TYT+Turkce",
                            Name = "Limit TYT Türkçe Soru Bankası",
                            Price = 240m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 10,
                            CategoryId = 4,
                            Description = "Çözümlü",
                            ImageUrl = "https://placehold.co/400x400?text=Limit+AYT+Edebiyat",
                            Name = "Limit AYT Edebiyat Soru Bankası",
                            Price = 260m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 11,
                            CategoryId = 4,
                            Description = "Video Çözümlü",
                            ImageUrl = "https://placehold.co/400x400?text=Sarmal+TYT+Mat",
                            Name = "Bilgi Sarmal TYT Matematik",
                            Price = 295m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 11,
                            CategoryId = 4,
                            Description = "Soru Bankası",
                            ImageUrl = "https://placehold.co/400x400?text=Sarmal+11+Fizik",
                            Name = "Bilgi Sarmal 11. Sınıf Fizik",
                            Price = 220m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 12,
                            CategoryId = 4,
                            Description = "Zor Seviye",
                            ImageUrl = "https://placehold.co/400x400?text=3D+TYT+Matematik",
                            Name = "3D TYT Matematik Simülasyon",
                            Price = 310m,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 12,
                            CategoryId = 4,
                            Description = "Tamamı Çözümlü",
                            ImageUrl = "https://placehold.co/400x400?text=3D+AYT+Geometri",
                            Name = "3D AYT Geometri",
                            Price = 280m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 13,
                            CategoryId = 4,
                            Description = "Set Halinde",
                            ImageUrl = "https://placehold.co/400x400?text=Cap+TYT+Fizik",
                            Name = "Çap TYT Fizik Fasikülleri",
                            Price = 350m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 14,
                            CategoryId = 4,
                            Description = "Hızlandırılmış",
                            ImageUrl = "https://placehold.co/400x400?text=Hiz+LGS+Paragraf",
                            Name = "Hız Yayınları 8. Sınıf LGS Paragraf",
                            Price = 180m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 14,
                            CategoryId = 4,
                            Description = "Yeni Nesil",
                            ImageUrl = "https://placehold.co/400x400?text=Hiz+LGS+Matematik",
                            Name = "Hız Yayınları 8. Sınıf LGS Matematik",
                            Price = 195m,
                            StockQuantity = 450
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 15,
                            CategoryId = 4,
                            Description = "Klasikleşmiş",
                            ImageUrl = "https://placehold.co/400x400?text=Palme+TYT+Kimya",
                            Name = "Palme TYT Kimya Soru Bankası",
                            Price = 250m,
                            StockQuantity = 220
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 15,
                            CategoryId = 4,
                            Description = "Konu Anlatımlı",
                            ImageUrl = "https://placehold.co/400x400?text=Palme+10+Biyoloji",
                            Name = "Palme 10. Sınıf Biyoloji",
                            Price = 270m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 16,
                            CategoryId = 4,
                            Description = "LGS Hazırlık",
                            ImageUrl = "https://placehold.co/400x400?text=Tonguc+8+Matematik",
                            Name = "Tonguç 8. Sınıf Dinamo Matematik",
                            Price = 210m,
                            StockQuantity = 600
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 16,
                            CategoryId = 4,
                            Description = "Taktikli Soru Bankası",
                            ImageUrl = "https://placehold.co/400x400?text=Tonguc+Paragrafiks",
                            Name = "Tonguç TYT Paragrafiks",
                            Price = 175m,
                            StockQuantity = 450
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 17,
                            CategoryId = 5,
                            Description = "Metal Fileli",
                            ImageUrl = "https://placehold.co/400x400?text=MAS+Organizer",
                            Name = "MAS Masaüstü Organizer Set Siyah",
                            Price = 240m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 17,
                            CategoryId = 5,
                            Description = "Yedek Tel",
                            ImageUrl = "https://placehold.co/400x400?text=MAS+Zimba+Teli",
                            Name = "MAS No:10 Zımba Teli 1000'li",
                            Price = 25m,
                            StockQuantity = 800
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 18,
                            CategoryId = 5,
                            Description = "Paslanmaz Çelik",
                            ImageUrl = "https://placehold.co/400x400?text=Maped+Makas",
                            Name = "Maped 21cm Ofis Makası",
                            Price = 75m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 18,
                            CategoryId = 5,
                            Description = "20 Sayfa Kapasite",
                            ImageUrl = "https://placehold.co/400x400?text=Maped+Delgec",
                            Name = "Maped Ergonomik Delgeç",
                            Price = 165m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 19,
                            CategoryId = 5,
                            Description = "Büyük Boy",
                            ImageUrl = "https://placehold.co/400x400?text=Pritt+Stick",
                            Name = "Pritt Stick Yapıştırıcı 43g",
                            Price = 65m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 19,
                            CategoryId = 5,
                            Description = "Çok Amaçlı",
                            ImageUrl = "https://placehold.co/400x400?text=Pritt+Sivi",
                            Name = "Pritt Sıvı Yapıştırıcı",
                            Price = 55m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 1,
                            CategoryId = 5,
                            Description = "İz Bırakmaz",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+Tack-It",
                            Name = "Faber-Castell Tack-It Hamur Yapıştırıcı",
                            Price = 45m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 5,
                            CategoryId = 5,
                            Description = "Silinebilir",
                            ImageUrl = "https://placehold.co/400x400?text=Bic+Tahta+Kalemi",
                            Name = "Bic Beyaz Tahta Kalemi 4'lü",
                            Price = 120m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 1,
                            CategoryId = 6,
                            Description = "Toz Bırakmaz",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+Dust-Free",
                            Name = "Faber-Castell Dust-Free Sınav Silgisi",
                            Price = 25m,
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 1,
                            CategoryId = 6,
                            Description = "Haznesiz",
                            ImageUrl = "https://placehold.co/400x400?text=Faber+Metal+Kalemtiras",
                            Name = "Faber-Castell Çift Delikli Metal Kalemtıraş",
                            Price = 45m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 2,
                            CategoryId = 6,
                            Description = "Yumuşak Silgi",
                            ImageUrl = "https://placehold.co/400x400?text=Rotring+Silgi",
                            Name = "Rotring Tikky Silgi 2'li",
                            Price = 35m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 3,
                            CategoryId = 6,
                            Description = "Renkli",
                            ImageUrl = "https://placehold.co/400x400?text=Stabilo+Silgi",
                            Name = "Stabilo Legacy Silgi",
                            Price = 20m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 18,
                            CategoryId = 6,
                            Description = "Dökülmez",
                            ImageUrl = "https://placehold.co/400x400?text=Maped+Shaker",
                            Name = "Maped Shaker Hazneli Kalemtıraş",
                            Price = 58m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 18,
                            CategoryId = 6,
                            Description = "Korumalı",
                            ImageUrl = "https://placehold.co/400x400?text=Maped+Salyangoz",
                            Name = "Maped Salyangoz Silgi",
                            Price = 35m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 20,
                            CategoryId = 6,
                            Description = "İspanyol Yapımı",
                            ImageUrl = "https://placehold.co/400x400?text=Milan+430+Silgi",
                            Name = "Milan 430 Klasik Kauçuk Silgi",
                            Price = 15m,
                            StockQuantity = 600
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 20,
                            CategoryId = 6,
                            Description = "2'si 1 Arada",
                            ImageUrl = "https://placehold.co/400x400?text=Milan+Capsule",
                            Name = "Milan Capsule Silgili Kalemtıraş",
                            Price = 85m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 56,
                            BrandId = 21,
                            CategoryId = 7,
                            Description = "500'lü Paket",
                            ImageUrl = "https://placehold.co/400x400?text=Navigator+A4",
                            Name = "Navigator A4 80g Fotokopi Kağıdı",
                            Price = 165m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 57,
                            BrandId = 6,
                            CategoryId = 7,
                            Description = "10 Renk",
                            ImageUrl = "https://placehold.co/400x400?text=Gipta+Elisi+Kagidi",
                            Name = "Gıpta Renkli A4 Elişi Kağıdı",
                            Price = 45m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 58,
                            BrandId = 6,
                            CategoryId = 7,
                            Description = "Su Geçirmez",
                            ImageUrl = "https://placehold.co/400x400?text=Gipta+Yapiskanli+Notluk",
                            Name = "Gıpta Şeffaf Yapışkanlı Notluk",
                            Price = 35m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 59,
                            BrandId = 22,
                            CategoryId = 7,
                            Description = "Koli Bazlı Fotokopi Kağıdı",
                            ImageUrl = "https://placehold.co/400x400?text=Mopak+A4+Kutu",
                            Name = "Mopak A4 80g Kutu (5 Paket)",
                            Price = 800m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 60,
                            BrandId = 22,
                            CategoryId = 7,
                            Description = "20'li Paket",
                            ImageUrl = "https://placehold.co/400x400?text=Mopak+Resim+Kagidi",
                            Name = "Mopak Resim Kağıdı 25x35",
                            Price = 40m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 61,
                            BrandId = 23,
                            CategoryId = 7,
                            Description = "75x75 Yapışkanlı",
                            ImageUrl = "https://placehold.co/400x400?text=Ve-Ge+Kup+Not",
                            Name = "Ve-Ge Sarı Küp Not",
                            Price = 25m,
                            StockQuantity = 600
                        },
                        new
                        {
                            Id = 62,
                            BrandId = 23,
                            CategoryId = 7,
                            Description = "Çizim İçin",
                            ImageUrl = "https://placehold.co/400x400?text=Ve-Ge+Aydinger",
                            Name = "Ve-Ge Aydınger Kağıdı A4",
                            Price = 120m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 63,
                            BrandId = 24,
                            CategoryId = 8,
                            Description = "Klasik Sırt Çantası",
                            ImageUrl = "https://placehold.co/400x400?text=Eastpak+Padded",
                            Name = "Eastpak Padded Pak'r Siyah",
                            Price = 1850m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 64,
                            BrandId = 24,
                            CategoryId = 8,
                            Description = "Tek Bölmeli",
                            ImageUrl = "https://placehold.co/400x400?text=Eastpak+Benchmark",
                            Name = "Eastpak Benchmark Kalemlik",
                            Price = 450m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 65,
                            BrandId = 4,
                            CategoryId = 8,
                            Description = "Sırt Destekli",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Canta",
                            Name = "Adel Ortopedik İlkokul Çantası",
                            Price = 750m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 66,
                            BrandId = 4,
                            CategoryId = 8,
                            Description = "Kilitli",
                            ImageUrl = "https://placehold.co/400x400?text=Adel+Beslenme+Kabi",
                            Name = "Adel 3 Bölmeli Çelik Beslenme Kabı",
                            Price = 320m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 67,
                            BrandId = 18,
                            CategoryId = 8,
                            Description = "BPA İçermez",
                            ImageUrl = "https://placehold.co/400x400?text=Maped+Suluk",
                            Name = "Maped Picnik Concept Suluk 430ml",
                            Price = 295m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 68,
                            BrandId = 18,
                            CategoryId = 8,
                            Description = "Mikrodalgaya Girebilir",
                            ImageUrl = "https://placehold.co/400x400?text=Maped+Beslenme+Kutusu",
                            Name = "Maped Çift Katlı Beslenme Kutusu",
                            Price = 350m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 69,
                            BrandId = 25,
                            CategoryId = 9,
                            Description = "Çelik Mekanizmalı",
                            ImageUrl = "https://placehold.co/400x400?text=Noki+Klasor",
                            Name = "Noki A4 Geniş Klasör Mavi",
                            Price = 85m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 70,
                            BrandId = 25,
                            CategoryId = 9,
                            Description = "A4 Uyumlu Föy",
                            ImageUrl = "https://placehold.co/400x400?text=Noki+Poset+Dosya",
                            Name = "Noki 100'lü Şeffaf Poşet Dosya",
                            Price = 95m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 71,
                            BrandId = 17,
                            CategoryId = 9,
                            Description = "Şeffaf Evrak Taşıma",
                            ImageUrl = "https://placehold.co/400x400?text=MAS+Citcitli+Dosya",
                            Name = "MAS Çıtçıtlı Zarf Dosya 10'lu",
                            Price = 75m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 72,
                            BrandId = 17,
                            CategoryId = 9,
                            Description = "Plastik",
                            ImageUrl = "https://placehold.co/400x400?text=MAS+Telli+Dosya",
                            Name = "MAS Telli Dosya 50'li Paket",
                            Price = 150m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 73,
                            BrandId = 6,
                            CategoryId = 9,
                            Description = "Sabit Föylü",
                            ImageUrl = "https://placehold.co/400x400?text=Gipta+Sunum+Dosyasi",
                            Name = "Gıpta Sunum Dosyası 40 Yaprak",
                            Price = 95m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 74,
                            BrandId = 6,
                            CategoryId = 9,
                            Description = "13 Bölmeli",
                            ImageUrl = "https://placehold.co/400x400?text=Gipta+Evrak+Cantasi",
                            Name = "Gıpta Körüklü Evrak Çantası",
                            Price = 220m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 75,
                            BrandId = 26,
                            CategoryId = 9,
                            Description = "Çekmece İçi",
                            ImageUrl = "https://placehold.co/400x400?text=Esselte+Askili+Dosya",
                            Name = "Esselte Askılı Dosya 25'li",
                            Price = 450m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 76,
                            BrandId = 26,
                            CategoryId = 9,
                            Description = "Karton Kapak",
                            ImageUrl = "https://placehold.co/400x400?text=Esselte+Dar+Klasor",
                            Name = "Esselte Dar Klasör Siyah",
                            Price = 80m,
                            StockQuantity = 120
                        });
                });

            modelBuilder.Entity("Stationery.Models.StationeryUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Stationery.Models.StationeryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Stationery.Models.StationeryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stationery.Models.StationeryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Stationery.Models.StationeryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stationery.Models.Cart", b =>
                {
                    b.HasOne("Stationery.Models.StationeryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stationery.Models.CartItem", b =>
                {
                    b.HasOne("Stationery.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stationery.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Stationery.Models.Order", b =>
                {
                    b.HasOne("Stationery.Models.StationeryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stationery.Models.OrderItem", b =>
                {
                    b.HasOne("Stationery.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stationery.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Stationery.Models.Product", b =>
                {
                    b.HasOne("Stationery.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stationery.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Stationery.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Stationery.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Stationery.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Stationery.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
